augment:
  color_jitter:
    brightness: 0.3
    contrast: 0.3
    hue: 0.2
    saturation: 0.3
  horizontal_flip: true
  rotation: 0
autoencoder:
  decoder:
    activation: ReLU
    kernel_size: 4
    num_layers: 4
    use_skip_connection: false
  latent_channels: 1280
data:
  dataset_path: datasets/screw
  image_size: 512
  use_masked: true
mask:
  blur_ksize: 15
  dataset_path: datasets/screw/test
  mask_path: datasets/screw/test/seg_mask
  min_contour_area: 1
  thresh_method: binary
  thresh_val: 183
model:
  name: efficientnetv2_s
  pretrained: false
  pretrained_path: models/files/efficientnet_v2_s_pre.pth
  save_path: models/files
training:
  batch_size: 20
  learning_rate: 0.0005
  loss_function: MSE
  num_epochs: 90
